version: "3.9"
services:
  backend:
    container_name: backend
    build: ./setupExpressRDS
    ports:
      - "8080:8080"
    restart: on-failure
  frontend:
    container_name: frontend
    build: ./setupReactMobx
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - backend